name: Build test project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_NAME: test

jobs:
#  init:
#    runs-on: self-hosted
#    strategy:
#      matrix:
#        target:
#          - go_builder
#    steps:
#      - uses: TooMuch4U/actions-clean@v2.1
#      - uses: actions/checkout@v4
#        with:
#          submodules: true
#      - run: |
#          docker build -f ./base.Dockerfile \
#          -t ${{ env.PROJECT_NAME }}_base:${{ matrix.target }} \
#          --target ${{ matrix.target }} \
#          --tag base:${{ matrix.target }} \
#          --cache-from type=gha,scope=${{ env.PROJECT_NAME }}_base:${{ matrix.target }} \
#          --cache-to type=gha,mode=max,scope=${{ env.PROJECT_NAME }}_base:${{ matrix.target }} \
#          .

  backend:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
#    needs:
#      - init
    strategy:
      matrix:
        target:
          - pingserver
          - hiserver
    steps:
      - uses: TooMuch4U/actions-clean@v2.1
      - uses: actions/checkout@v4
      - name: Login to GitHub Package Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

      - name: Start build ${{ env.PROJECT_NAME }} - ${{ matrix.target }}
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/${{ env.PROJECT_NAME }}-${{ matrix.target }}
          echo START BUILD WITH IMAGE_ID=$IMAGE_ID

          PATH_TO_MAIN=${{ matrix.target }}
          echo PATH_TO_MAIN=$PATH_TO_MAIN

          docker buildx build -f ./apps/apps.Dockerfile \
          --build-arg PATH_TO_MAIN=$PATH_TO_MAIN \
          --tag $IMAGE_ID:latest \
          --cache-from type=gha,scope=${{ env.PROJECT_NAME }}:${{ matrix.target }} \
          --cache-to type=gha,mode=max,scope=${{ env.PROJECT_NAME }}:${{ matrix.target }} \
          -t ${{ env.PROJECT_NAME }}:${{ matrix.target }} \
          .

          docker push $IMAGE_ID:latest